name: mindkeeper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  url_launcher: ^6.1.7
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8

dependency_overrides:
  flutter_local_notifications_linux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
